# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1My9tAy3n7eZhWwUgCFJP_ye036tywL9L
"""

# Install required libraries (run once)
!pip install transformers torch

# Import libraries
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

# Load GPT-2 model and tokenizer
print("Loading model...")
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Set model to evaluation mode
model.eval()

# Function to generate text
def generate_text(prompt):
    input_ids = tokenizer.encode(prompt, return_tensors="pt")

    output = model.generate(
        input_ids,
        max_length=150,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        temperature=0.8,
        top_k=50,
        top_p=0.95,
        do_sample=True
    )

    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return generated_text

# Main program
if __name__ == "__main__":
    print("\n--- GPT-2 Text Generator ---")

    # User input
    prompt = input("Enter your prompt: ")

    # Generate text
    result = generate_text(prompt)

    print("\nGenerated Text:\n")
    print(result)

    # Save output to file
    with open("output.txt", "w") as f:
        f.write(result)

    print("\n✅ Output saved to output.txt")